imports = [
  "display-manager",
  "drivers",
  "firewall",
  # "flatpak",
  "lang",
  # "laptop",
  "network",
  "services",
  "software",
  "themes",
  "virtualization",
  "wm",
]

[managers.runit]
items = []

[managers.system]
items = []

[managers.aur]
items = ["cava", "freetube-bin", "mutt-wizard", "oh-my-posh", "zen-browser-bin"]

[managers.go]
items = []

[managers.cargo]
items = []
