[managers.system]
items = [
  "bridge-utils",
  "dnsmasq",
  "dosfstools",
  "libvirt",
  "libvirt-runit",
  "lxc",
  "qemu-full",
  "swtpm",
  "uefi-run",
  "virt-manager",
  "virt-viewer",
]

[managers.runit]
items = ["libvirtd"]
