[managers.system]
items = [
  # "brave",
  # "ddgr",
  # "firefox",
  # "floorp",
  "lynx",
  # "nyxt",
  # "qutebrowser",
  # "vivaldi",
  # "w3m",
]

[managers.aur]
items = [
  # "librewolf",
  # "ungoogled-chromium"
]
