[managers.system]
items = [
  "age",
  # "atomicparsley",
  "bash-completion",
  "bat",
  # "bc",
  # "borgbackup",
  # "bpytop",
  "brightnessctl",
  "btop",
  "cmatrix",
  "cmus",
  "cryptsetup",
  "curl",
  "direnv",
  # "expect",
  "eza",
  "fastfetch",
  "fd",
  "ffmpeg",
  "figlet",
  "fzf",
  "git",
  "git-crypt",
  "github-cli",
  "gitleaks",
  "gnupg",
  # "gnutar", # Not in pacman
  "gocryptfs",
  "gvfs",
  "imagemagick",
  # "jmtpfs", # Not in pacman
  "jq",
  "just",
  # "killall", # Not in pacman
  "lazygit",
  "less",
  # "libargon2",
  "lsof",
  "man",
  "moreutils",
  "mpv",
  "mtpfs",
  "mupdf",
  "mupdf-tools",
  # "navi",
  "ncdu",
  "newsboat",
  "nmap",
  "oath-toolkit",
  # "odt2txt",
  "onefetch",
  # "opendoas",
  "openssh",
  "openssl",
  "pandoc",
  "playerctl",
  # "pulseaudio",
  # "pwgen",
  "ranger",
  "rclone",
  "restic",
  "ripgrep",
  # "rmlint", # Not in pacman
  "rsync",
  "sd",
  "sqlite",
  "srm",
  "stow",
  "tldr",
  "tmux",
  "tmuxp",
  "tree",
  "ueberzugpp",
  "ufw",
  "unzip",
  "wget",
  "yazi",
  "yt-dlp",
  "zip",
  "zoxide",
]
