[managers.system]
items = [
  # "gocryptfs"
  "pass",
  "pass-otp",
  # "pass-tomb", # Not in pacman
  # "steghide", # Not in pacman
  # "tomb", # Not in pacman
  "zbar",
]

[managers.aur]
items = [
  "lesspass",
]
