[managers.system]
items = [
  "cliphist",
  "dunst",
  "fuzzel",
  "grim",
  "libnotify",
  "pavucontrol",
  "rofi-wayland",
  "satty",
  "slurp",
  "swayimg",
  "swww",
  "wf-recorder",
  # "wttrbar", # Not in pacman
  "ydotool",
]
