[managers.system]
items = [
  "dconf",
  "dmenu",
  "dunst",
  "feh",
  "flameshot",
  "libnotify",
  "nsxiv",
  "picom",
  "redshift",
  "rofi",
  "sxhkd",
  "xclip",
  "xclip",
  "xdotool",
  "zenity",
  # "adwaita-qt", # Not in pacman
]
