[managers.system]
items = [
  "adwaita-qt",
  # "clipcat",
  "dconf",
  "feh",
  "flameshot",
  "libnotify",
  "networkmanagerapplet",
  "nsxiv",
  "redshift",
  "sxhkd",
  "xclip",
  "xclip",
  "xdotool",
  "zenity",
]
