[managers.system]
items = [
  "clang",
  "gcc",
  "gdb",
  "git",
  "gvfs",
  "linux",
  "linux-firmware",
  "lld",
  "llvm",
  "parted",
  "udisks2",
  "unzip",
  "vim",
  "xfsdump",
  "xfsprogs",

  "zip",
  "gvfs",
  "mtpfs",
  "gvfs-mtp",
  "polkit",
  "udiskie",
  "udisks2",
  "fuse2",
  "unzip",
  "zip",
  "direnv",
  "atomicparsley",
  "zsh",
  "ueberzugpp",
  "gnome-keyring",
  "playerctl",
  "ydotool",
  "brightnessctl",
  "at",
  "pacman-contrib",
  "task",
  "timewarrior",
  "taskwarrior-tui",

  # CLI
  "rsync",
  "pass",
  "tmux",
  "pass-otp",
  "gocryptfs",
  "ffmpeg",
  "mpv",
  "cmus",
  "git",
  "stow",
  "ufw",
  # "opendoas",
  "gnupg",
  "onefetch",
  "fastfetch",
  "lynx",
  "ranger",
  "bpytop",
  "eza",
  "fd",
  "fzf",
  "github-cli",
  "tldr",
  "man",
  "lazygit",
  "zoxide",
  "ripgrep",
  "bat",
  "cmatrix",
  "figlet",
  "tmuxp",
  "cmus",
  "gitleaks",
  "moreutils",
  "navi",
  "imagemagick",
  "just",
  "neomutt",
  "syncthing",
  "neovim",
  "mupdf",
  "mupdf-tools",
  "yt-dlp",
  "newsboat",
  "ddgr",
  "odt2text",

  # Graphical
  "seahorse",
  "obsidian",
  "libreoffice-fresh",
  "shotcut",
  "gnome-disk-utility",
  "obs-studio",
  "gimp",
  "dmenu",
  "dunst",
  "neovide",
  "kitty",
  "foot",
  "picom",
  "scrcpy",
  "rofi-calc",
  "rofi",
  # "networkmanager-openvpn",
  "fuzzel",
  "swayimg",
  "grim",
  "slurp",
  "satty",
  "pavucontrol",

  # Fonts
  "noto-fonts-emoji",
  "gnu-free-fonts",
  "ttf-ubuntu-nerd",
  "ttf-fira-code",
  "ttf-dejavu-nerd",
  "ttf-jetbrains-mono-nerd",
  "ttf-gabarito-git",

  # CLI
  "age",
  "# atomicparsley",
  "bash-completion",
  "bat",
  # "bc",
  "brightnessctl",
  "btop",
  "cmus",
  "cryptsetup",
  "curl",
  "direnv",
  "# expect",
  "eza",
  "fastfetch",
  "fd",
  "ffmpeg",
  "figlet",
  "fzf",
  "gh",
  "git",
  "git-crypt",
  "gitleaks",
  "gnutar",
  "gocryptfs",
  "gvfs",
  "home-manager",
  "imagemagick",
  "jmtpfs",
  "jq",
  "just",
  "killall",
  "lazygit",
  "less",
  "libargon2",
  "lsof",
  "man",
  "moreutils",
  "mtpfs",
  "mupdf",
  "ncdu",
  "nmap",
  "oath-toolkit",
  # "odt2txt",
  "oh-my-posh",
  "onefetch",
  "openssl",
  "openssh",
  "flatpak",
  "polkit",
  # "pulseaudio",
  "pwgen",
  "ranger",
  "ripgrep",
  "rmlint",
  "rsync",
  "sd",
  "sqlite",
  "srm",
  "stow",
  "tldr",
  "tmux",
  "tmuxp",
  "tree",
  "ueberzugpp",
  "unzip",
  "wget",
  "yazi",
  "ydotool",
  "yt-dlp",
  "zip",
  "zoxide",

  # Emacs
  "emacs",
  "emacs-lsp-booster",
  "ffmpegthumbnailer",
  "graphviz",
  "mediainfo",
  "poppler_utils",
  "vips",

  # Email
  "isync",
  "mutt-wizard",
  "neomutt",
  # "thunderbird",

  # Neovim
  "neovim",
  "neovide",
  "alejandra",
  "bash-language-server",
  # "clang-tools",
  # "docker-compose-language-service",
  # "dockerfile-language-server-nodejs",
  "harper",
  # "java-language-server",
  # "kotlin-language-server",
  "lua-language-server",
  "markdown-oxide",
  "marksman",
  "neovide",
  # "sqls",
  # "typescript-language-server",
  # "yaml-language-server",

  # Pass
  "tomb",
  "pass",
  "pass-tomb",
  "pass-otp",
  "zbar",
  "steghide",
]

[managers.paru]
items = [
  "cava",
  "freetube-bin",
  "mutt-wizard",
  "oh-my-posh",
  "zen-browser-bin",
  "rose-pine-gtk-theme",
]
