imports = [
  "software/browser",
  "software/cli",
  # "software/emacs",
  "software/encryption",
  "software/fonts",
  "software/lsp",
  "software/mail",
  "software/media",
  "software/neovim",
  "software/office",
  "software/others",
  # "software/proprietary/obsidian",
  # "software/proprietary/steam",
  "software/shell",
  "software/syncthing",
  "software/task",
  "software/terminal",
  "software/text-editor",
  "software/xdg",
]
