[managers.system]
items = [
  "qemu-full",
  "virt-manager",
  "virt-viewer",
  "dnsmasq",
  "bridge-utils",

  "libvirt",
  "virt-manager",
  "qemu",
  "uefi-run",
  "lxc",
  "swtpm",
  "dosfstools",
]
